defaultIndent: "  "

specialBeginEnd:
  inlineMath:
    # https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-specialbeginend
    lookForThis: 0 # don't indent inline math

  # known bug with this block: if a \href is found in $$...$$, it causes problems
  # braces:
  #   begin: \{
  #   end: \}
  #   lookForThis: 0
  # specialBeforeCommand: 1

removeTrailingWhitespace: 1
noAdditionalIndent:
  textit: 1
  textbf: 1
  href: 1

modifyLineBreaks:
  condenseMultipleBlankLinesInto: 1
  textWrapOptions:
    when: after
    columns: 80
    blocksEndBefore:
      other: \\begin\{|\\end\{|\$\$
    huge: overflow # forbid mid-word line breaks
    separator: ""

lookForAlignDelims:
  vmat: 1
  bmat: 1
  pmat: 1
  align*:
    delims: 1
    spacesAfterAmpersand: 0

onlyOneBackUp: 1
